# GitHub Actions CI for Go project
# Runs tests, vet, and lint on push and pull request

name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run go fmt
        run: go fmt ./...

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Check for outdated dependencies
        run: go list -u -m -mod=readonly all

      - name: Run govulncheck (dependency audit)
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Check go.mod/go.sum tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
        shell: bash
        # Fails if go.mod or go.sum are not tidy


      - name: Run tests
        run: go test -v ./...

      - name: Run staticcheck (optional)
        uses: dominikh/staticcheck-action@v1
        with:
          version: "2023.1.3"
        continue-on-error: true
